CREATE TABLE IF NOT EXISTS Client (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL CHECK (LENGTH(name) >= 3)
    );

CREATE TABLE IF NOT EXISTS Planet (
    id VARCHAR(20) NOT NULL PRIMARY KEY CHECK (id REGEXP '^[A-Z0-9]+$'),
    name VARCHAR(500) CHECK (LENGTH(name) >= 1)
    );

CREATE TABLE IF NOT EXISTS Ticket (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    client_id BIGINT NOT NULL,
    from_planet_id VARCHAR(20) NOT NULL,
    to_planet_id VARCHAR(20) NOT NULL,
    FOREIGN KEY (client_id) REFERENCES Client(id) ON DELETE CASCADE,
    FOREIGN KEY (from_planet_id) REFERENCES Planet(id) ON DELETE CASCADE,
    FOREIGN KEY (to_planet_id) REFERENCES Planet(id) ON DELETE CASCADE
    );